name: Build and Push to DockerHub

on:
  push:
    branches:
      - chains/coreum-v0.50.x

jobs:
  build-publish-docker:
    name: Build and Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Start ssh-agent and add keys for private imports
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.TX_CHAIN_PRIVATE_KEY }}
            ${{ secrets.TX_CRUST_PRIVATE_KEY }}
            ${{ secrets.TX_JUNO_PRIVATE_KEY }}
            ${{ secrets.TX_TOOLS_PRIVATE_KEY }}
            
      - name: Setup access to private repositories
        run: |
          export GOPRIVATE=github.com/tokenize-x GONOSUMDB=github.com/tokenize-x
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          echo -e "${{ secrets.TX_CHAIN_PRIVATE_KEY }}" > ~/.ssh/tx-chain-deploy-key
          echo -e "${{ secrets.TX_CRUST_PRIVATE_KEY }}" > ~/.ssh/tx-crust-deploy-key
          echo -e "${{ secrets.TX_TOOLS_PRIVATE_KEY }}" > ~/.ssh/tx-tools-deploy-key
          echo -e "${{ secrets.TX_JUNO_PRIVATE_KEY }}" > ~/.ssh/tx-juno-deploy-key
          chmod 600 ~/.ssh/tx-chain-deploy-key ~/.ssh/tx-crust-deploy-key ~/.ssh/tx-tools-deploy-key ~/.ssh/tx-juno-deploy-key
          {
            echo -e "Host tx-chain-private\n    HostName github.com\n    User git\n    StrictHostKeyChecking no\n    IdentityFile ~/.ssh/tx-chain-deploy-key\n    IdentitiesOnly yes"
            echo -e "Host tx-crust-private\n    HostName github.com\n    User git\n    StrictHostKeyChecking no\n    IdentityFile ~/.ssh/tx-crust-deploy-key\n    IdentitiesOnly yes"
            echo -e "Host tx-tools-private\n    HostName github.com\n    User git\n    StrictHostKeyChecking no\n    IdentityFile ~/.ssh/tx-tools-deploy-key\n    IdentitiesOnly yes"
            echo -e "Host tx-juno-private\n     HostName github.com\n    User git\n    StrictHostKeyChecking no\n    IdentityFile ~/.ssh/tx-juno-deploy-key\n    IdentitiesOnly yes"
          } > ~/.ssh/config
          {
            echo -e "[url \"git@tx-chain-private:tokenize-x/tx-chain\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-chain\""
            echo -e "[url \"git@tx-crust-private:tokenize-x/tx-crust\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-crust\""
            echo -e "[url \"git@tx-tools-private:tokenize-x/tx-tools\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-tools\""
            echo -e "[url \"git@tx-juno-private:tokenize-x/tx-juno\"]\n          insteadOf = \"https://github.com/tokenize-x/tx-juno\""
          } > ~/.gitconfig
          
      - name: Add github.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
          
      - name: Prefer SSH for GitHub URLs
        run: |
          git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
          
      - name: Build and publish images
        run: make release-images
